version: "3.9"

services:
  # ───────────────────────────── Datastore ─────────────────────────────
  db:
    image: mysql:8.0
    container_name: mysql-container
    user: "999:999"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE:      ${MYSQL_DATABASE}
      MYSQL_USER:          ${MYSQL_USER}
      MYSQL_PASSWORD:      ${MYSQL_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ─────────────────────────────── API ─────────────────────────────────
  api:
    build: .
    container_name: api-server
    user: "1000:1000"
    depends_on:
      db:
        condition: service_healthy

    ports:
      - "443:443"                  # public API
    environment:
      API_ADDR:      ${API_ADDR}
      METRICS_ADDR:  ${METRICS_ADDR}
      DB_HOST:       ${DB_HOST}
      DB_PORT:       ${DB_PORT}
      DB_NAME:       ${DB_NAME}
      DB_USER:       ${DB_USER}
      DB_PASSWORD:   ${DB_PASSWORD}
      CERTS_HOST_DIR: ${CERTS_HOST_DIR}

    volumes:
      - ./engine/static:/app/static
      - ${CERTS_HOST_DIR}:/tls:ro

  # ──────────────────────────── Prometheus ─────────────────────────────
  prometheus:
    image: prom/prometheus:v3.4.1
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.config.file=/etc/prometheus/web.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-lifecycle"
    volumes:
      - ./deploy/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ${PROM_BASIC_AUTH_FILE}:/etc/prometheus/web.yml:ro
      - prometheus_data:/prometheus

  # ───────────────────────────── Grafana (optional) ────────────────────
  #grafana:
  #  image: grafana/grafana:12.0.2
  #  container_name: grafana
  #  restart: always
  #  depends_on: [prometheus]
  #  ports:
  #    - "3000:3000"
  #  env_file:
  #    - /etc/engine/secret.env
  #  environment:
  #    GF_SECURITY_ADMIN_USER:     ${GF_SECURITY_ADMIN_USER}
  #    GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
  #    GF_USERS_ALLOW_SIGN_UP:     ${GF_USERS_ALLOW_SIGN_UP}
  #  volumes:
  #    - grafana_data:/var/lib/grafana

volumes:
  db_data:
  prometheus_data:
  #grafana_data:
