version: '3.8'

secrets:
  db_root_password:   { file: ./secrets/db_root_password.txt }
  db_password:        { file: ./secrets/db_password.txt }
  api_secret_key:     { file: ./secrets/secret_key.txt }

services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    user: "999:999"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
    secrets:           
      - db_root_password
      - db_password

  api:
    build:
      context: .
    container_name: api-server
    user: "1000:1000" 
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "443:443"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD_FILE: /run/secrets/db_password
      SECRET_KEY_FILE: /run/secrets/api_secret_key
    secrets:
      - db_password
      - api_secret_key
volumes:
  db_data:
