services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    user: "999:999"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my_root_password
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
    container_name: api-server
    user: "1000:1000" 
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "1234:1234"
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      SECRET_KEY: jwt_secret_key
volumes:
  db_data:
